Add newline between attributes
apple/swift-syntax pull request #1511
Opened 2023-04-09 19:07 UTC by kimdv

Fixes #1504

2023-04-09 21:57 UTC, stevapple requested changes

2023-04-09 21:57 UTC, stevapple commented on Sources/SwiftBasicFormat/generated/BasicFormat.swift
> +    case (.identifier, .keyword):
Add a comment explaining what it’s going to solve?

2023-04-09 21:57 UTC, stevapple commented on CodeGeneration/Sources/SyntaxSupport/AttributeNodes.swift
> +    elementsSeparatedByNewline: true
We may need `elementsSeparatedBySpace` instead… Splitting the attribute list with newlines looks terrible, especially when they’re applied to a declaration without leading newline trivia.

2023-04-09 21:57 UTC, stevapple commented on Tests/SwiftSyntaxBuilderTest/FunctionTests.swift
> +                attributes: [.attribute(AttributeSyntax("@discardableResult"))],
Try multiple attributes here?

2023-04-11 07:16 UTC, kimdv commented
Do you think we should add newline or a whitespace between @stevapple?

2023-04-11 07:20 UTC, stevapple commented
I would prefer whitespaces to newlines for wherever it's applicable (aka. legal in Swift).

2023-04-11 12:24 UTC, kimdv commented
I've been looking into some swift code and cannot conclude what is the best practice to do or if the `BasicFormat` should support it. 
IMO a newline is fine so it will generate valid swift and we can use what we already have. 

Then we can also avoid having the special handling `case (.identifier, .keyword):` inside `BasicFormat`

What do you think of that?

2023-04-11 12:35 UTC, stevapple commented
Newlines are not very bad, but the current implementation will produce
```swift
@inlinable
@discardableResult
@available(*, deprecated, message: "Use print directly instead") public func hello() -> Int {
    print("Hello world!")
    return 0
}
```
which looks really weird.

The main reason to prefer whitespace is that, when we want to a newline we can always add `.with(\.trailingTrivia, .newline)`, but if we default to newline the reverse just won’t work.

2023-04-11 15:21 UTC, stevapple commented
Separating attributes with newlines maybe more troublesome than it seems… After some investigation.

```swift

let buildable = FunctionDeclSyntax(
  identifier: "hello",
  signature: .init(
    input: .init(
      parameterList: [
        FunctionParameterSyntax(
          attributes: [.attribute("@NameBuilder")],
          firstName: "name",
          type: AttributedTypeSyntax(
            attributes: [.attribute("@escaping"), .attribute("@Sendable")],
            baseType: FunctionTypeSyntax(
              arguments: [],
              output: .init(returnType: TypeSyntax("String"))
            )
          )
        )
      ]
    )
  ),
  body: .init(
    statements: [
      .init(item: .decl(#"print("Hello, \(name())!")"#))
    ]
  )
)
print(buildable.formatted())
```

Gives:
```swift
func hello(
    @NameBuilder
    name: 
    @escaping
    @Sendable
    () -> String) {print("Hello, \(name())!")
}
```

Which is, IMO, valid but almost unacceptable.

2023-04-11 15:51 UTC, kimdv commented
I see.. hmm.
Then we either should handle case by case or only add white space and let users add new line.

2023-04-11 15:53 UTC, stevapple commented
I would suggest the latter, leaving case-by-case formatting for `swift-format`.

2023-04-11 21:35 UTC, ahoppen commented
> At least we should have a way to opt out of these new lines, which I didn’t see at the moment.

Just for the record, I don’t think we should add many customization options to `BasicFormat`. It is called `BasicFormat` for a reason: It’s goal is to format a SwiftSyntax tree in a way that, most importantly, parses and, secondly, doesn’t look terrible. I am fine with requiring users to subclass `BasicFormat` if they want to customize it.

2023-04-12 03:57 UTC, stevapple commented
@ahoppen I didn’t meant to add the option to `BasicFormat` actually. In existing APIs we already can use explicit newlines over spaces by setting the trivia manually, without touching `BasicFormat` at all.

You can see my use case in https://github.com/teco-project/teco-code-generators, which is used to generate ~1 million lines of nice-looking code with `SwiftSyntaxBuilder`, with little modification to `BasicFormat`.

2023-04-25 07:13 UTC, kimdv commented
@ahoppen changed this to add some test cases that for #1504

2023-04-25 07:15 UTC, kimdv commented
@swift-ci please test

2023-04-25 07:20 UTC, stevapple approved these changes
Looks good overall!

2023-04-25 07:20 UTC, stevapple commented on Tests/SwiftSyntaxBuilderTest/SourceFileTests.swift
> +      import UIKit
Looks like a regression here. Is this intentional?

2023-04-25 07:21 UTC, stevapple commented
Should there be test cases for #1472 and #1551 too?

2023-04-25 10:51 UTC, kimdv commented
@swift-ci please test

2023-04-25 12:54 UTC, kimdv commented
@swift-ci please test windows

2023-04-25 16:16 UTC, ahoppen approved these changes

2023-04-25 16:16 UTC, ahoppen commented on Tests/SwiftSyntaxBuilderTest/TriviaTests.swift
> +        @A @B
I would prefer this string literal to continue being single line so you can actually see the trailing whitespace.

2023-04-25 18:44 UTC, kimdv commented
@swift-ci please test

2023-04-25 21:39 UTC, merged