[5.9][CMake] Use WMO for release builds
apple/swift-syntax pull request #1699
Opened 2023-05-24 21:58 UTC by bnbarham

* Explanation: CMake builds were not using WMO for release (this is fixed in 3.26+). This has a significant impact on parsing times (5x).
* Scope: swift-syntax libraries included in the compiler
* Risk: Very low. Just enables WMO for release builds.
* Original PR: https://github.com/apple/swift-syntax/pull/1692

2023-05-24 21:58 UTC, bnbarham commented
@swift-ci please test

2023-05-24 22:16 UTC, ahoppen approved these changes

2023-05-26 14:18 UTC, compnerd requested changes

2023-05-26 14:18 UTC, compnerd commented on cmake/modules/AddSwiftHostLibrary.cmake
> +  if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
Please pull in #1705 if this is going to be merged.

2023-08-05 22:19 UTC, closed without merging