Make sure we convert the source to a native UTF-8 string before parsing
apple/swift-syntax pull request #251
Opened 2020-12-01 16:55 UTC by ahoppen

It appears like the compiler is now optimizing the `self += ""` away in release builds. Furthermore, we didn't catch the issue since the assertion checking for a native UTF-8 string also gets optimized away in release builds.

Fix the issue in two ways:
1. Make the assertion a precondition that also fails in release builds
2. Generate the native UTF-8 string through an iterator that indexes into the foreign string. This is a much more complex transformation and harder to optimize away. It also should be a big performance hit since the Swift standard library also loops over the foreign string to generate a native one.

2020-12-01 16:55 UTC, ahoppen commented
@swift-ci Please test

2020-12-01 17:31 UTC, akyrtzi commented
@milseman do you maybe have another recommendation for forcing a native UTF8 string?
We also use this:
```
  var isNativeUTF8: Bool {
    return utf8.withContiguousStorageIfAvailable { _ in 0 } != nil
  }
```

2020-12-01 17:46 UTC, milseman commented
Are you able to use Swift 5.1? [SE-0247 Contiguous Strings](https://github.com/apple/swift-evolution/blob/main/proposals/0247-contiguous-strings.md) provides the preferred API on String: `var isContiguousUTF8: Bool` and `mutating func makeContiguousUTF8()`.

2020-12-01 17:52 UTC, milseman commented
If you cannot use Swift 5.1, let's come up with a solution that doesn't assemble and then disassemble grapheme clusters. Have you tried something like `self = String(decoding: self.utf16, as: UTF16.self)` if you know it's a bridged fully-UTF-16 Cocoa string? You can compare that performance to `self = String(decoding: self.utf8, as: UTF8.self)`.

2020-12-01 17:53 UTC, akyrtzi commented
We can use Swift 5.1, thank you!

2020-12-02 00:36 UTC, akyrtzi requested changes
Let's use the String APIs that are provided for this kind of functionality.

2020-12-02 08:43 UTC, ahoppen commented
Thanks for the pointer @milseman, that’s a much cleaner solution.

@swift-ci Please test.

2020-12-02 17:30 UTC, akyrtzi approved these changes

2020-12-02 17:30 UTC, merged