SyntaxArena: thread safety
apple/swift-syntax pull request #807
Opened 2022-09-16 23:29 UTC by rintaro

Use mutex to guard concurrent mutation to the arena.

2022-09-16 23:31 UTC, rintaro commented
@swift-ci Please test

2022-09-16 23:32 UTC, rintaro commented
@swift-ci Please test

2022-09-19 08:09 UTC, jpsim commented
Thank you, this certainly helps, although TSan now reports an access race in the guard code:

```

WARNING: ThreadSanitizer: Swift access race (pid=42514)
  Modifying access of Swift variable at 0x0001148c22b0 by thread T25:
    #0 ScopeGuard.withGuard<A>(body:) <null>:82026728 (SwiftLintFrameworkTests:arm64+0x126a334)
    #1 SyntaxArena.withGuard<A>(body:) <null>:82026728 (SwiftLintFrameworkTests:arm64+0x126b504)
    #2 SyntaxArena.allocateRawSyntaxBuffer(count:) <null>:82026728 (SwiftLintFrameworkTests:arm64+0x126c2fc)
    #3 static RawSyntax.makeLayout(kind:uninitializedCount:arena:initializingWith:) <null>:82026728 (SwiftLintFrameworkTests:arm64+0xffcd14)
    #4 RawSyntaxLayoutView.replacingChild(at:with:arena:) <null>:82026728 (SwiftLintFrameworkTests:arm64+0x10036c8)
    #5 SyntaxData.replacingChild(_:at:) <null>:82026728 (SwiftLintFrameworkTests:arm64+0x1285864)
```

Full report: https://buildkite.com/swiftlint/swiftlint/builds/3411#018354b5-95eb-4c14-ab21-f7d59113f241

2022-09-19 14:33 UTC, ahoppen commented on Sources/SwiftSyntax/SyntaxArena.swift
> +    let allocated = lock.withGuard {
Same here, should this be `self.withGuard`?

2022-09-19 20:37 UTC, CodaFi commented on Sources/SwiftSyntax/SyntaxArena.swift
>  public class SyntaxArena {
Can we allocate these locks inline with the arena blocks?

2022-09-19 21:10 UTC, CodaFi requested changes
These ScopeGuards are not correct. We cannot use the materialization operator here despite the fact that we're indexing through a heap allocation for the member access - it's still a logical data race even if it's not always a physical data race. These locks need to be allocated out-of-line and the resulting address passed.

2022-09-20 22:20 UTC, CodaFi approved these changes

2022-09-20 22:23 UTC, rintaro commented
@jpsim I confirmed the failure locally. And the modified implementation resolves it. Could you check the new implementation?

2022-09-20 22:23 UTC, rintaro commented
@swift-ci Please test

2022-09-21 02:18 UTC, jpsim approved these changes
There are no more TSan failures in my testing. Thank you!

2022-09-21 03:24 UTC, merged